version: '2'
services:
  hanoi-coffee-api:
    container_name: hanoi-coffee-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
