version: '3'

services:
  mongo:
    container_name: hanoi-coffee-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - hanoi-coffee-mongo:/data/db
      - ./docker/mongo/rs-init.sh:/scripts/mongo/rs-init.sh
    networks:
      - mongo-compose-network
    env_file:
      - .env

  postgres:
    container_name: hanoi-coffee-postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - hanoi-coffee-postgres:/data/postgres
      - ./docker/postgres/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    restart: always
    networks:
      - postgres-network

  redis:
    container_name: hanoi-coffee-redis
    image: 'redis:alpine'
    volumes:
      - hanoi-coffee-redis:/data
    ports:
      - 6379:6379

  zipkin-all-in-one:
    container_name: hanoi-coffee-zipkin-all-in-one
    image: openzipkin/zipkin:latest
    ports:
      - '9411:9411'
    env_file:
      - .env

  prometheus:
    container_name: hanoi-coffee-prometheus
    image: prom/prometheus:v2.47.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=otlp-write-receiver'
      - '--enable-feature=exemplar-storage'
    env_file:
      - .env
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml

  collector:
    container_name: hanoi-coffee-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/conf/collector-config.yaml']
    volumes:
      - ./docker/collector/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - '9464:9464'
      - '4317:4317'
      - '4318:4318'
    depends_on:
      - zipkin-all-in-one

  mongo-express:
    container_name: hanoi-coffee-mongo-express
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
    env_file:
      - .env
    # environment:
    #   - ME_CONFIG_MONGODB_SERVER=mongo

  pgadmin:
    container_name: hanoi-coffee-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  hanoi-coffee-postgres:
  hanoi-coffee-redis:
  hanoi-coffee-mongo:

networks:
  mongo-compose-network:
    driver: bridge
  postgres-network:
    driver: bridge
