version: '2'
services:
  microservice-api:
    container_name: microservice-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src
